services:
  # iniciate db for api 
  db: 
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    volumes:
      # iniciate volume for db for tests
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql